url: https://zeroart.github.io
# baseurl: /agency-jekyll-theme/
host: localhost

# Site settings
title: 冰冰的家
email: miss.wbingbing@gmail.com
description: "Design Comes From Life,Pursue Inspiration In Life"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: C1F5C4
  secondary: ece473
  secondary-dark: 355c7d

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty